#!/usr/bin/expect -f 

  set backuplist "ip.txt"
  set logpath "."
  set log_file "./backup.log.txt"
  set tftp_server "192.168.122.178"
  set data [exec date +%d/%m/%Y-%H:%M]
  set timeout 20
  log_file "./backup.log.txt"

  #Cria diretorio (se nao existe)
  if {!([file exists $logpath])} then {
      set MakeDir [exec mkdir $logpath]}

  set host ""
  set user "roberto"
  set pass "abc@123"

  # telnet 
  set lista [open $backuplist r]
        while {[gets $lista host] > 0} {
                sleep 1
                spawn ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $user@$host

                expect "*word:"     
                send "$pass\r"

#                expect {   
#                "denied*"     { 
#                send_user "\nLogin $host falied. Passowrd incorrect.\n"; continue ; 2>> | grep falied $log_file

                expect "*#"
                send "copy running tftp:\r$tftp_server\r$host\r"

    		expect "*#"
                send "exit\r"

		log_file
            	}  
closel $lista
